/*
 * Copyright 2026 The NablaTensor Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.nablatensor.engine.jit;

/**
 * The interface the generated tape-specific class implements. One instance is
 * built per tape; a replay is two virtual calls, each dispatching into
 * straight-line generated bytecode.
 */
public interface JitKernel {

  /**
   * Forward sweep for one scenario: fills {@code v} (one slot per tape node),
   * reading differentiable inputs from {@code in} and this path's pre-generated
   * normal draws from {@code draws}, and returns {@code v[output]}. {@code scratch}
   * is the rolled kernel's step-tape (ignored by the flat kernel; may be empty).
   */
  double forward(double[] v, double[] in, double[] draws, double[] scratch);

  /**
   * Reverse sweep: {@code d} arrives zeroed except {@code d[output] == 1.0};
   * on return it holds the adjoint of every node, so {@code d[inputNode[j]]} is
   * the gradient w.r.t. input {@code j}. {@code scratch} carries the forward
   * step-tape for the rolled kernel.
   */
  void reverse(double[] v, double[] d, double[] scratch, double[] draws);
}
